
::aa::आ
::aadab::आदाब
::aadat::आदत
::aadesh::आदेश
::aadha::आधा
::aadhi::आधी
::aadmi::आदमी
::aaee::आयी
::aaenge::आयेंगे
::aage::आगे
::aai::आयी
::aaine::आईने
::aaj::आज
::aajkal::आज कल
::aake::आके
::aakhir::आखिर
::aalu::आलू
::aana::आना
::aane::आने
::aani::आनि
::aankhen::आँखें
::aankhon::आंखों
::aao::आओ
::aaoge::आओगे
::aaogi::आओगी
::aap::आप
::aapka::आपका
::aapke::आपके
::aapki::आपकी
::aapko::आपको
::aapne::आप्ने
::aapse::आपसे
::aaraam::आराम
::aaram::आराम
::aarti::आरती
::aarzoo::आरज़ू
::aata::आता
::aate::आते
::aati::आती
::aatma::आत्मा
::aaun::आऊं
::aaunga::आऊंगा
::aaya::आया
::aaye::आये
::aayee::आयी
::aayega::आयेगा
::aayegi::आयेगी
::aayenge::आयेंगे
::aayi::आयी
::ab::अब
::abe::अबे
::abhi::अभी
::accha::अच्छा
::acche::अच्छे
::acchi::अच्छी
::acha::अच्छा
::achaar::अचार
::achaari::अचारी
::achar::अचार
::achari::अचारी
::ache::अच्छे
::achi::अच्छी
::ada::अदा
::adha::आधा
::adhi::आधी
::adrak::अदरक
::agar::अगर
::agla::अगला
::agle::अगले
::agli::अगली
::aisa::ऐसा
::aise::ऐसे
::aisi::ऐसी
::aji::अजी
::akela::अकेला
::akele::अकेले
::akeli::अकेली
::allah::अल्लाह
::aloo::आलू
::altoo::आलतू
::alu::आलू
::anda::अंडा
::andar::अन्दर
::ande::अंडे
::andhera::अँधेरा
::andhere::अँधेरे
::anek::अनेक
::aogi::आओगी
::apka::आपका
::apmaan::अपमान
::apman::अपमान
::apna::अपना
::apne::अप्ने
::apni::अपनी
::ardhangini::अर्धांगिनी
::arre::अररे
::arz::अर्ज़
::arzoo::आरज़ू
::atma::आत्मा
::aunga::आऊंगा
::aur::और
::ayenge::आयेंगे
::baad::बाद
::baadme::बाद में
::baahon::बाहों
::baaki::बाकी
::baal::बाल
::baandh::बाँध
::baap::बाप
::baar::बार
::baare::बारे
::baari::बारी
::baarish::बारिश
::baat::बात
::baatein::बातें
::baatu::बातु
::babu::बाबू
::baccha::बच्छा
::bacche::बच्छे
::bacchon::बच्छों
::bach::बच
::bacha::बचा
::bachake::बचाके
::bachana::बचाना
::bachane::बचाने
::bachao::बचाओ
::bache::बचे
::bachke::बचके
::bachpan::बचपन
::bada::बढ़ा
::badati::बढाती
::badboo::बदबू
::badbu::बदबू
::bade::बढ़े
::badh::बढ़
::badhne::बढ़ने
::badhta::बढ़ता
::badhte::बढ़ते
::badhti::बढ़ती
::badi::बढ़ी
::badiya::बढ़िया
::badiyan::बढियाँ
::badmash::बदमाश
::badnaseeb::बदनसीब
::badnasibi::बदनसीबी
::badne::बढ़ने
::badsurat::बदसूरत
::badta::बढ़ता
::badte::बढ़ते
::badti::बढ़ती
::bagal::बगल
::bahar::बाहर
::bahut::बहुत
::baith::बैठ
::baithe::बैठे
::baithke::बैठके
::baithne::बैठने
::baitho::बैठो
::baiti::बैठी
::baitthe::बैठते
::baj::बज
::bajao::बजाओ
::baje::बजे
::bajne::बजने
::bak::बक
::baki::बाकी
::bako::बको
::bakta::बकता
::bakvas::बकवास
::bakwas::बकवास
::balle::बल्ले
::ban::बन
::bana::बना
::banadunga::बनादूंगा
::banake::बनाके
::banana::बनाना
::banane::बनाने
::banao::बनाओ
::banata::बनाता
::banati::बनाती
::banaunga::बनाऊंगा
::banaungi::बनाउंगी
::banaya::बनाया
::banayega::बनायेगा
::banayegi::बनायेगी
::banayein::बनायें
::banayenge::बनायेंगे
::banda::बंदा
::bandar::बंदर
::bandh::बंध
::bandhu::बंधु
::banega::बनेगा
::banegi::बनेगी
::banenge::बनेंगे
::bann::बन
::banne::बन्ने
::bano::बनो
::banoge::बनोगे
::banta::बनता
::bante::बनते
::banti::बनती
::baren::बारे
::bari::बारी
::barish::बारिश
::bas::बस
::bata::बता
::batana::बताना
::batane::बताने
::batao::बताओ
::batata::बताता
::batate::बताते
::batati::बताती
::bataun::बताऊँ
::bataya::बताया
::batayenge::बताएँगे
::batu::बातु
::bawarchi::बावर्ची
::bechara::बेचारा
::bechare::बेचारे
::bechari::बेचारी
::beech::बीच
::behen::बेहेन
::beta::बेटा
::bete::बेटे
::beti::बेटी
::bevajah::बेवजह
::bhaag::भाग
::bhaaga::भागा
::bhaagi::भागी
::bhaago::भागो
::bhaari::भारी
::bhag::भाग
::bhago::भागो
::bhai::भाई
::bhaiya::भैय्या
::bhaiyya::भैय्या
::bhaji::भाजी
::bhala::भला
::bhar::भर
::bharana::भराना
::bharatiya::भारतीय
::bhari::भारी
::bharta::भरता
::bhatura::भटूरा
::bhayya::भैय्या
::bheeg::भीग
::bheega::भीगा
::bheegi::भीगी
::bhej::भेज
::bheja::भेजा
::bheji::भेजी
::bhejke::भेजके
::bhejna::भेजना
::bhejne::भेजने
::bhejo::भेजो
::bhejoge::भेजोगे
::bhejogi::भेजोगी
::bhejta::भेजता
::bhejti::भेजती
::bhi::भी
::bhikari::भिकारी
::bhook::भूक
::bhooka::भूका
::bhookamp::भूकंप
::bhookh::भूख
::bhool::भूल
::bhoolna::भूलना
::bhugathna::भुगतना
::bhugatna::भुगतना
::bhugtho::भुगतो
::bhugto::भुगतो
::bhuk::भूक
::bhukh::भूख
::bichad::बिछड़
::bichadke::बिछडके
::bichadna::बिछड़ना
::bichadne::बिछड़ने
::bigad::बिगड़
::bigada::बिगाडा
::bigadta::बिगड़ता
::bigadti::बिगड़ती
::bilkul::बिल्कुल
::billi::बिल्ली
::bimari::बीमारी
::bina::बिना
::biwi::बीवी
::biwiyaan::बीवीयाँ
::biwiyan::बीवीयाँ
::bol::बोल
::bola::बोला
::bolat::बोलत
::bole::बोले
::bolega::बोलेगा
::bolegi::बोलेगी
::bolenge::बोलेंगे
::boli::बोली
::boliye::बोलिए
::bolna::बोलना
::bolne::बोलने
::bolo::बोलो
::bologe::बोलोगे
::bologi::बोलोगी
::bolta::बोलता
::bolte::बोलते
::bolti::बोलती
::bolun::बोलूं
::bolunga::बोलूँगा
::bolungi::बोलूंगी
::bubbu::बुब्बू
::budda::बुढ्ढा
::budde::बूढ़े
::buddhe::बूढ़े
::buddi::बुढ्ढी
::budhe::बूढ़े
::bukh::भूख
::bula::बुला
::bulana::बुलाना
::bulao::बुलाओ
::bulaoge::बुलाओगे
::bulaogi::बुलाओगी
::bulata::बुलाता
::bulate::बुलाते
::bulati::बुलाती
::bulaun::बुलाऊँ
::bulaya::बुलाया
::bulayega::बुलायेगा
::bulayegi::बुलायेगी
::bulayenge::बुलायेंगे
::bura::बुरा
::buri::बुरी
::byah::ब्याह
::chaabi::चाबी
::chaal::चाल
::chaanta::चांटा
::chaar::चार
::chabi::चाबी
::chado::छडो
::chadte::छड़ते
::chadti::छड़ती
::chahe::चाहे
::chahenge::चाहेंगे
::chahiye::चाहिये
::chahta::चाहता
::chahti::चाहती
::chai::चाय
::chaiye::चाहिये
::chal::चल
::chala::चला
::chalak::चालाक
::chalake::चलाके
::chalana::चलाना
::chalane::चलाने
::chalaun::चलाऊं
::chale::चले
::chalega::चलेगा
::chalegi::चलेगी
::chalen::चलें
::chali::चली
::chaliye::चलिये
::chalke::चलके
::chalna::चलना
::chalne::चलने
::chalo::चलो
::chalta::चलता
::chalte::चलते
::chalti::चलती
::chana::चना
::chandi::चाँदी
::changa::चंगा
::changi::छंगी
::channa::चना
::chanti::చంటి
::chaon::छाओं
::chaprasi::चपरासी
::char::चार
::che::छे
::chee::छी
::cheeni::चीनी
::cheez::चीज़
::cheezen::चीज़ें
::cheezon::चीज़ों
::chhado::छडो
::chhadte::छड़ते
::chhadti::छड़ती
::chhalo::चलो
::chi::छी
::chidiya::चिड़िया
::chilka::चिल्का
::chilke::छिलके
::chilla::चिल्ला
::chillake::चिल्लाके
::chillana::चिल्लाना
::chillao::चिल्लाओ
::chillata::चिल्लाता
::chillate::चिल्लाते
::chillati::चिल्लाती
::chinta::चिंता
::chintak::चिंतक
::chod::छोड़
::chodna::छोड़ना
::chodne::छोड़ने
::chodo::छोड़ो
::chodoge::छोडोगे
::chodta::छोड़ता
::chodte::छोड़ते
::chodti::छोड़ती
::chole::छोले
::chona::छोना
::choni::छोनी
::choo::छू
::chooe::छूए
::chooke::छूके
::choona::छूना
::choone::छूने
::choota::छूता
::choote::छूते
::chooti::छूती
::chota::छोटा
::chote::छोटे
::choti::छोटी
::chotu::छोटू
::chua::छुआ
::chudel::चुडेल
::chuk::चुक
::chukar::छूकर
::chun::चुन
::chuna::छूना
::chuo::छुओ
::chup::चुप
::daal::डाल
::daala::डाला
::daalen::डालें
::daalke::डालके
::daalte::डालते
::dahi::दही
::dal::दाल
::dala::डाला
::dalenge::डालेंगे
::dalo::डालो
::dalta::डालता
::dalte::डालते
::dalti::डालती
::dar::डर
::de::दे
::deewar::दीवार
::dehati::देहाती
::deke::देके
::dekh::देख
::dekha::देखा
::dekhe::देखे
::dekhega::देखेगा
::dekhen::देखें
::dekhenge::देखेंगे
::dekhi::दखी
::dekhiye::देखिये
::dekhke::देखके
::dekhna::देखना
::dekhne::देखने
::dekho::देखो
::dekhoge::देखोगे
::dekhogi::देखोगी
::dekhta::देखता
::dekhte::देखते
::dekhti::देखती
::dekhunga::देखूंगा
::dekhungi::देखूंगी
::dena::देना
::denge::देंगे
::der::देर
::desh::देश
::desi::देसी
::deta::देता
::dete::देते
::deten::देतें
::deti::देती
::dhaam::धाम
::dhadak::धड़क
::dhadakna::धड़कना
::dhadakne::धड़कने
::dhadakta::धड़कता
::dhadakti::धड़कती
::dhakkan::ढक्कन
::dheela::ढीला
::dheele::ढीले
::dheere::धीरे
::dho::दो
::dhona::धोना
::dhone::धोने
::dhong::ढोंग
::dhongini::ढ़ोंगिनी
::dhoond::ढूंड
::dhoondke::ढूंडके
::dhoondo::ढूंडो
::dhoondoge::ढूंडोगे
::dhoondogi::ढूंडोगी
::dhoop::धूप
::di::दी
::didi::दीदी
::dikh::दिख
::dikha::दिखा
::dikhana::दिखाना
::dikhane::दिखाने
::dikhao::दिखाओ
::dikhata::दिखाता
::dikhate::दिखाते
::dikhati::दिखाती
::dikhaya::दिखाया
::dikhne::दिखने
::dikhta::दिखता
::dikhte::दिखते
::dikhti::दिखती
::dikkat::दिक्खत
::dikkhat::दिक्खत
::dil::दिल
::dilbar::दिलबर
::dimaag::दिमाग
::dimag::दिमाग
::din::दिन
::diya::दिया
::diye::दिये
::doge::दोगे
::dogi::दोगी
::doh::दो
::dono::दोनों
::doodh::दूध
::doosra::दूसरा
::doosre::दूसरे
::doosri::दूसरी
::doosron::दूसरों
::dost::दोस्त
::duddhu::दुधु
::dudh::दूध
::dudhu::दुधू
::dukh::दुःख
::dukhi::दुखी
::dun::दूँ
::dunga::दूंगा
::dungi::दूंगी
::duniya::दुनिया
::dur::दूर
::dus::दस
::dusra::दूसरा
::dusri::दूसरी
::ek::एक
::faida::फायदा
::faltoo::फालतू
::farmaaish::फ़र्माइश
::farmaish::फ़र्माइश
::fayda::फायदा
::gaa::गा
::gaadi::गाड़ी
::gaadiyan::गाडियाँ
::gaana::गाना
::gaane::गाने
::gaiye::गाइये
::galat::ग़लत
::gale::गले
::galti::गलती
::gana::गाना
::ganda::गंदा
::gande::गंदे
::gandi::गंदी
::ganja::गंजा
::ganje::गंजे
::ganji::गंजी
::gao::गाओ
::gappe::गप्पे
::gapshap::गपशप
::garam::गरम
::garma::गरमा
::garmi::गर्मी
::gaya::गया
::gaye::गये
::gayi::गयी
::ghar::घर
::ghatthe::घटते
::ghoom::घूम
::ghoomi::घूमी
::ghulam::घुलाम
::ghulami::घुलामी
::ghus::घुस
::ghusaake::घुसाके
::ghusaana::घुसाना
::ghusaata::घुसाता
::ghusaate::घुसाते
::ghusaati::घुसाती
::ghusake::घुसाके
::ghusana::घुसाना
::ghusata::घुसाता
::ghusate::घुसाते
::ghusati::घुसाती
::ghuske::घुसके
::ghusna::घुसना
::ghusne::घुसने
::ghusta::घुसता
::ghuste::घुसते
::ghusti::घुसती
::gi::गी
::gir::गिर
::gira::गिरा
::giraya::गिराया
::girenge::गिरेंगे
::giri::गिरी
::giro::गिरो
::giroge::गिरोगे
::girogi::गिरोगी
::girte::गिरते
::gobar::गोबर
::godi::गोदी
::gora::गोरा
::gorey::गोरे
::gori::गोरी
::gubbare::गुब्बारे
::gupshup::गपशप
::gussa::ग़ुस्सा
::gusse::गुस्से
::haal::हाल
::haan::हाँ
::haath::हाथ
::haathon::हाथों
::hadap::हड़प
::hafta::हफ्ता
::hafte::हफ्ते
::hai::है
::hain::हैं
::haina::है ना
::haldi::हल्दी
::halka::हल्का
::halwa::हलवा
::hamaara::हमारा
::hamara::हमारा
::hamare::हमारे
::hamari::हमारी
::hamen::हमें
::hamesha::हमेशा
::hansi::हँसी
::hanso::हँसो
::hansta::हँसता
::hanste::हँसते
::hansti::हँसती
::har::हर
::haram::हराम
::hasane::हँसाने
::hasata::हँसाता
::hasate::हँसाते
::hasati::हँसाती
::haso::हसो
::hasta::हँसता
::hastey::हँसते
::hasti::हँसती
::hatt::हट
::hatya::हत्या
::hazir::हाज़िर
::hee::ही
::hii::ही
::hila::हिला
::hilake::हिलाके
::hilna::हिलना
::hilne::हिलने
::hindi::हिन्दी
::ho::हो
::hoga::होगा
::hogi::होगी
::hona::होना
::hone::होने
::honge::होंगे
::honi::होनी
::hoon::हूँ
::hota::होता
::hote::होते
::hoti::होती
::hoya::होया
::hu::हूँ
::hua::हुआ
::hue::हुए
::hui::हुई
::hum::हम
::humare::हमारे
::humesha::हमेशा
::humko::हमको
::humne::हमने
::humse::हमसे
::hun::हूँ
::hunga::हूँगा
::hungi::हूंगी
::hutt::हट
::huzoor::हुज़ूर
::huzur::हुज़ूर
::idhar::इधर
::ilaaka::इलाका
::ilaake::इलाके
::ilaka::इलाका
::ilake::इलाके
::inhone::इन्होंने
::inka::इनका
::inke::इनके
::inki::इनकी
::insaan::इनसान
::irada::इरादा
::irshaad::इरशाद
::irshad::इरशाद
::ishq::इश्क
::isiliye::इसीलिये
::iska::इसका
::iske::इसके
::iski::इसकी
::isko::इसको
::isliye::इसलिए
::isme::इसमे
::ispe::इसपे
::iss::इस
::isse::इससे
::itna::इतना
::itne::इतने
::itni::इतनी
::ja::जा
::jaa::जा
::jaake::जाके
::jaan::जान
::jaana::जाना
::jaanam::मुबारक
::jaane::जाने
::jaani::जानी
::jaanta::जानता
::jaante::जानते
::jaanti::जानती
::jaanvar::जानवर
::jaata::जाता
::jaate::जाते
::jaati::जाती
::jaaun::जाऊं
::jaaye::जाये
::jaayen::जायें
::jab::जब
::jagah::जगह
::jahan::जहाँ
::jai::जय
::jaisa::जैसा
::jaise::जैसे
::jaisi::जैसी
::jaldi::जल्दी
::jale::जले
::janaab::जनाब
::janab::जनाब
::jani::जानी
::janu::जानू
::janvar::जानवर
::jao::जाओ
::jaoge::जाओगे
::jaogi::जाओगी
::jarurat::ज़रूरत
::jata::जाता
::jati::जाती
::jaun::जाऊं
::jaunga::जाऊंगा
::jaungi::जाउंगी
::jawab::जवाब
::jawan::जवान
::jawani::जवानी
::jaye::जाए
::jayega::जायेगा
::jayegi::जायेगी
::jayenge::जायेंगे
::jee::जी
::jeena::जीना
::jeene::जीने
::jeeta::जीता
::jeete::जीते
::jeeti::जीती
::jhagad::झगड़
::jhagadke::झगड़के
::jhagadna::झगड़ना
::jhagadne::झगड़ने
::jhagda::झगड़ा
::jhak::झक
::jhelna::झेलना
::jhelta::झेलता
::jhelte::झेलते
::jhelti::झेलती
::jhooth::झूठ
::ji::जी
::jis::जिस
::jiska::जिसका
::jiski::जिसकी
::jisko::जिसको
::jitna::जितना
::jitne::जितने
::jitni::जितनी
::jiya::जिया
::jiye::जिये
::jiyo::जियो
::jo::जो
::jodi::जोड़ी
::juda::जुदा
::jul::जुल
::julm::ज़ुल्म
::jyaada::ज्यादा
::jyada::ज़्यादा
::ka::का
::kaafi::काफ़ी
::kaala::काला
::kaam::काम
::kaamu::कामु
::kab::कब
::kabhi::कभी
::kabr::कब्र
::kada::కద
::kadar::कदर
::kafa::कफा
::kafi::काफ़ी
::kaha::कहा
::kahan::कहाँ
::kahani::कहानी
::kahi::कही
::kahin::कहीँ
::kaho::कहो
::kahoge::कहोगे
::kahunga::कहूँगा
::kahungi::कहूँगी
::kaisa::कैसा
::kaise::कैसे
::kaisi::कैसी
::kaku::काकू
::kal::कल
::kala::काला
::kam::कम
::kambakhat::कमबख्त
::kambakht::कमबख्त
::kambhakht::कमबख्त
::kambhakt::कमबख्त
::kamina::कमीना
::kamini::कमीनी
::kanjoos::कंजूस
::kanjoosi::कंजूसी
::kanjusi::कंजूसी
::kar::कर
::kara::करा
::karao::कराओ
::karata::कराता
::karate::कराते
::karati::कराती
::karaunga::कराऊंगा
::karaungi::कराऊंगी
::karaya::कराया
::kare::करें
::karega::करेगा
::karegi::करेगी
::karen::करें
::karenge::करेंगे
::karke::करके
::karlo::कर लो
::karna::करना
::karne::करने
::karo::करो
::karoge::करोगे
::karogi::करोगी
::karta::करता
::karte::करते
::karti::करती
::karun::करूँ
::karunga::करुंगा
::karungi::करुँगी
::karvaya::करवाया
::kasam::कसम
::kaun::कौन
::kauno::कौनो
::kaunsa::कौनसा
::kaunse::कौनसे
::kaunsi::कौनसी
::ke::के
::kee::की
::kehna::कहना
::kela::केला
::kele::केले
::kha::खा
::khaali::खाली
::khaana::खाना
::khaane::खाने
::khaaya::खाया
::khaayen::खायें
::khaayi::खायी
::khake::खाके
::khalenge::खालेंगे
::khali::खाली
::khaliya::खालिया
::khalo::खालो
::khalunga::खालूँगा
::khalungi::खालूंगी
::khana::खाना
::khane::खाने
::khao::खाओ
::khaoge::खाओगे
::khaogi::खाओगी
::kharab::ख़राब
::kharcha::खर्चा
::kharid::ख़रीद
::kharida::ख़रीदा
::kharidenge::खरीदेंगे
::kharidna::खरीदना
::kharidne::खरीदने
::kharido::ख़रीदो
::kharidoge::खरीदोगे
::kharidogi::खरीदोगी
::kharidta::खरीदता
::kharidte::खरीदते
::kharidtha::खरीदता
::kharidthe::खरीदते
::kharidthi::खरीदती
::kharidti::खरीदती
::kharidun::खरीदूं
::khat::ख़त
::khata::खाता
::khatam::ख़तम
::khatar::खटर
::khate::खाते
::khati::खाती
::khaunga::खाऊंगा
::khaungi::खाऊंगी
::khaya::खाया
::khayaal::ख़याल
::khayal::ख़याल
::khaye::खाये
::khayega::खायेगा
::khayen::खायें
::khayenge::खायेंगे
::khayi::खायी
::khel::खेल
::khela::खेला
::khele::खेले
::khelen::खेलें
::kheli::खेली
::khelna::खेलना
::khelne::खेलने
::khelo::खेलो
::khelta::खेलता
::khelte::खेलते
::khelti::खेलती
::khet::खेत
::khilona::खिलौना
::khit::खिट
::kho::खो
::khol::खोल
::kholke::खोलके
::kholna::खोलना
::kholne::खोलने
::kholta::खोलता
::kholte::खोलते
::kholti::खोलती
::khona::खोना
::khoob::खूब
::khoobsoorat::खूबसूरत
::khoobsurat::खूबसूरत
::khoya::खोया
::khub::खूब
::khubsurat::खूबसूरत
::khud::ख़ुद
::khul::खुल
::khula::खुला
::khulna::खुलना
::khulta::खुलता
::khulte::खुलते
::khulti::खुलती
::khusboo::खुशबू
::khusbu::खुशबू
::khush::खुश
::khushboo::खुशबू
::khushbu::खुशबू
::khushi::खुशी
::ki::की
::kidhar::किधर
::kijiye::कीजिये
::kintu::किंतु
::kis::किस
::kisi::किसी
::kisika::किसीका
::kisike::किसीके
::kisiki::किसीकी
::kisiko::किसीको
::kisine::किसीने
::kisise::किसीसे
::kiska::किसका
::kiske::किसके
::kiski::किसकी
::kisko::किसको
::kisliye::किसलिए
::kismat::किस्मत
::kisne::किसने
::kisse::किस्से
::kitna::कितना
::kitne::कितने
::kitni::कितनी
::kiya::किया
::kiye::किये
::ko::को
::koi::कोई
::koshish::कोशिश
::kripa::कृपा
::kuch::कुछ
::kuda::కూడా
::kum::कम
::kusboo::खुशबू
::kushboo::खुशबू
::kushbu::खुशबू
::kutta::कुत्ता
::kya::क्या
::kyon::क्यों
::kyoo::क्यूं
::kyoon::क्यूं
::kyu::क्यों
::kyun::क्यों
::laad::लाड
::laadla::लाडला
::laaj::लाज
::laake::लाके
::laal::लाल
::laane::लाने
::laaun::लाऊं
::laaya::लाया
::laaye::लाये
::laayenge::लायेंगे
::laayi::लायी
::lad::लड़
::ladai::लडाई
::ladka::लड़का
::ladke::लड़के
::ladki::लड़की
::ladkiyan::लड़कियां
::ladkiyon::लड़कियों
::ladla::लाडला
::ladne::लड़ने
::lado::लडो
::ladta::लड़ता
::ladte::लड़ते
::ladti::लड़ती
::lag::लग
::laga::लगा
::lagake::लगाके
::lagale::लगाले
::lagana::लगाना
::lagane::लगाने
::lagao::लगाओ
::lagaya::लगाया
::lage::लगे
::lagega::लगेगा
::lagi::लगी
::lagna::लगना
::lagta::लगता
::lagte::लगते
::lagti::लगती
::lal::लाल
::lala::लाला
::lallu::लल्लू
::lalu::लालू
::lamba::लम्बा
::lambi::लम्बी
::lao::लाओ
::laun::लाऊं
::launda::लौंडा
::launde::लौंडे
::launga::लाऊंगा
::laut::लौट
::lauta::लौटा
::laute::लौटे
::lauti::लौटी
::lautke::लौटके
::laye::लाये
::layenge::लायेंगे
::le::ले
::lega::लेगा
::legi::लेगी
::leke::लेके
::lekin::लेकिन
::lelo::ले लो
::lena::लेना
::lene::लेने
::lenge::लेंगे
::leta::लेता
::lete::लेते
::leti::लेती
::lijiye::लीजिये
::likh::लिख
::likha::लिखा
::likhlo::लिख्लो
::likho::लिखो
::likhta::लिखता
::likhte::लिखते
::likhti::लिखती
::liya::लिया
::liye::लिये
::lo::लो
::log::लोग
::loge::लोगे
::logon::लोगों
::loonga::लूँगा
::lun::लूँ
::lunga::लूँगा
::maa::माँ
::maaf::माफ़
::maafi::माफ़ी
::maahir::माहिर
::maal::माल
::maan::मान
::maana::माना
::maane::माने
::maangta::मांगता
::maangte::मांगते
::maangtha::मांगता
::maangthe::मांगते
::maangthi::मांगती
::maangti::मांगती
::maani::मानी
::maar::मार
::maarke::मारके
::maarna::मारना
::maarne::मारने
::maaro::मारो
::maarta::मारता
::maarte::मारते
::maarti::मारती
::maarunga::मारूंगा
::maf::माफ़
::mafi::माफ़ी
::magar::मगर
::mahan::महान
::mahina::महीना
::mahine::महीने
::mahir::माहिर
::mai::मैं
::maine::मैंने
::makhi::मक्खी
::maloom::मालूम
::malum::मालूम
::mama::मामा
::mana::मना
::manana::मनाना
::manao::मनाओ
::manega::मानेगा
::manegi::मानेगी
::manenge::मानेंगे
::mangta::मांगता
::mangte::मांगते
::mangtha::मांगता
::mangthe::मांगते
::mangthi::मांगती
::mangti::मांगती
::mann::मन
::manogi::मानोगी
::manta::मानता
::mante::मानते
::manti::मानती
::mar::मर
::marne::मरने
::maro::मरो
::marunga::मरूंगा
::marzi::मर्ज़ी
::masti::मस्ती
::mat::मत
::matashri::माताश्री
::matlab::मतलब
::matlabi::मतलबी
::mauj::मौज
::mausam::मौसम
::maza::मज़ा
::mazaak::मज़ाक
::mazak::मज़ाक
::mei::में
::mein::में
::mela::मेला
::memsaab::मेमसाहिब
::memsahib::मेमसाहिब
::mera::मेरा
::mere::मेरे
::meri::मेरी
::mil::मिल
::mila::मिला
::milake::मिलाके
::milane::मिलाने
::milega::मिलेगा
::milegi::मिलेगी
::milenge::मिलेंगे
::miley::मिले
::mili::मिली
::milke::मिलके
::milna::मिलना
::milne::मिलने
::milo::मिलो
::milta::मिलता
::milte::मिलते
::milti::मिलती
::moocche::मूछें
::moocchein::मूछें
::mooche::मूछें
::moochein::मूछें
::mota::मोटा
::mote::मोटे
::moti::मोटी
::motu::मोटू
::mubarak::मुबारक
::mucche::मूछें
::mujhe::मुझे
::mujhko::मुझको
::mujhse::मुझसे
::mundan::मुंडन
::munna::मुन्ना
::munni::मुन्नी
::murgi::मुर्गी
::murzi::मर्ज़ी
::mushkil::मुश्किल
::na::ना
::naach::नाच
::naacho::नाचो
::naachun::नाचूँ
::naak::नाक
::naam::नाम
::naari::नारी
::naate::नाते
::nach::नाच
::nacha::नचा
::nachata::नचाता
::nachate::नचाते
::nachati::नचाती
::nachun::नाचूँ
::nahi::नहीं
::nahin::नहीं
::nai::नाइ
::nakhre::नखरे
::namak::नमक
::namaste::नमस्ते
::nana::नाना
::nanga::नंगा
::nange::नंगे
::nangi::नंगी
::nangu::नंगू
::nanha::नन्हा
::nanhi::नन्ही
::nari::नारी
::naseeb::नसीब
::nata::नाता
::nau::नौ
::naya::नया
::naye::नये
::nayi::नयी
::nazar::नज़र
::ne::ने
::neeche::नीचे
::neend::नींद
::neenu::नीनू
::ni::नी
::nikaal::निकाल
::nikaala::निकाला
::nikaali::निकाली
::nikaalna::निकालना
::nikaalte::निकालते
::nikal::निकल
::nikalna::निकलना
::nikalne::निकलने
::nikalo::निकालो
::nikalta::निकलता
::nikalte::निकलते
::nikalti::निकलती
::nikla::निकला
::nikle::निकले
::niklenge::निकलेंगे
::nikli::निकली
::niklo::निकलो
::nikloge::निकलोगे
::niklun::निकलूं
::niklungi::निकलूंगी
::ninnu::निन्नू
::nok::नोक
::nunnu::नुन्नू
::om::ॐ
::paa::पा
::paagal::पागल
::paake::पाके
::paanch::पाँच
::paane::पाने
::paani::पानी
::paas::पास
::paav::पाँव
::pachtana::पछताना
::pachtane::पछताने
::pachtao::पछताओ
::pad::पड
::pada::पडा
::padd::पढ़
::paddna::पढ़ना
::paddne::पढ़ने
::paddta::पढ़ता
::paddte::पढ़ते
::paddti::पढ़ती
::pade::पडे
::padega::पड़ेगा
::padh::पढ़
::padha::पढ़ा
::padhke::पढ़के
::padhna::पढ़ना
::padhne::पढ़ने
::padho::पढो
::padhta::पढ़ता
::padhte::पढ़ते
::padhti::पढ़ती
::padi::पडी
::padke::पढ़के
::padna::पढ़ना
::pado::पढो
::padta::पडता
::padte::पडते
::padti::पडती
::paer::पैर
::paeron::पैरों
::pagal::पागल
::pahunch::पहुँच
::pahunchi::पहुँची
::pahunchna::पहुंचना
::pahunchogi::पहुँचोगी
::pahunchunga::पहुँचूँगा
::pahunchungi::पहुंचूंगी
::paida::पैदा
::pairon::पैरों
::paise::पैसे
::pakode::पकोडे
::palak::पालक
::panch::पाँच
::paneer::पन्नीर
::pani::पानी
::pappi::पप्पी
::par::पर
::parantha::पराठा
::paranthe::पराठे
::parantu::परन्तु
::paratha::पराठा
::parathe::पराठे
::parso::परसों
::parva::परवाह
::parvah::परवाह
::parwah::परवाह
::pas::पास
::pata::पता
::patangu::पतंगु
::patar::पटर
::pati::पति
::patni::पत्नी
::paun::पाऊं
::pav::पाँव
::payr::पैर
::pe::पे
::pee::पी
::peeche::पीछे
::peeke::पीके
::peena::पीना
::pehen::पहेन
::pehenke::पहेनके
::pehenta::पहेनता
::pehenti::पहेनती
::pehla::पहला
::pehle::पहले
::pehli::पहली
::pehno::पहनो
::pesh::पेश
::phataphat::फटाफट
::phenk::फ़ेंक
::phenkna::फेंकना
::phenko::फेंको
::phir::फिर
::phirse::फिर से
::phoda::फोडा
::phode::फोडे
::phodi::फोडी
::phodo::फोडो
::phooti::फूटी
::piche::पीछे
::pit::पिट
::pitashri::पिताश्री
::piya::पिया
::piyenge::पियेंगे
::piyo::पियो
::piyoge::पियोगे
::piyun::पियूं
::piyunga::पियूँगा
::piyungi::पियूँगी
::poocha::पूछा
::poochega::पूछेगा
::poochenge::पूछेंगे
::poochke::पूछके
::poocho::पूछो
::poochoge::पूछोगे
::poochogi::पूछोगी
::poochta::पूछता
::poochte::पूछते
::poochti::पूछती
::poonch::पूँछ
::prashan::प्रशन
::puch::पूछ
::pucha::पूछा
::puchega::पूछेगा
::puchenge::पूछेंगे
::puchke::पूछके
::pucho::पूछो
::puchoge::पूछोगे
::puchogi::पूछोगी
::pud::पड़
::puppu::पुप्पू
::pura::पूरा
::purana::पुराना
::purane::पुराने
::purani::पुरानी
::puri::पूरी
::pyaar::प्यार
::pyaaru::प्यारु
::pyar::प्यार
::pyaru::प्यारु
::raat::रात
::rab::रब
::raees::रईस
::rah::रह
::raha::रहा
::rahe::रहे
::rahen::रहें
::rahenge::रहेंगे
::rahi::रही
::rahna::रहना
::rahne::रहने
::raho::रहो
::rahoge::रहोगे
::rahogi::रहोगी
::rahta::रहता
::rahte::रहते
::rahti::रहती
::rahunga::रहूंगा
::raja::राजा
::raju::राजू
::rakh::रख
::rakha::रखा
::rakhi::रखी
::rakhna::रखना
::rakho::रखो
::rakhta::रखता
::rakhte::रखते
::rakhti::रखती
::rani::रानी
::rey::रे
::reh::रह
::rehke::रहके
::rehna::रहना
::rehne::रहने
::rehta::रहता
::rehti::रहती
::rishta::रिश्ता
::rishte::रिश्ते
::ro::रो
::roka::रोका
::roko::रोको
::rokta::रोकता
::rokte::रोकते
::rokti::रोकती
::rona::रोना
::rota::रोता
::rote::रोते
::roti::रोटी
::roz::रोज़
::ruk::रुक
::rukke::रुक्के
::rukna::रुकना
::rukne::रुकने
::ruko::रुको
::rukta::रुकता
::rukte::रुकते
::rukti::रूकती
::sa::सा
::saab::साब
::saaf::साफ़
::saal::साल
::saala::साला
::saale::साले
::saali::साली
::saamne::सामने
::saara::सारा
::saare::सारे
::saari::सारी
::saat::साथ
::saath::साथ
::saathi::साथी
::sab::सब
::sabka::सबका
::sabke::सबके
::sabki::सबकी
::sabko::सबको
::sabne::सबने
::sabse::सबसे
::sabzi::सब्ज़ी
::saccha::सच्चा
::sacchi::सच्ची
::safai::सफाई
::sahi::सही
::sahib::साहिब
::sahiba::साहिबा
::saka::सका
::saki::सकी
::sako::सको
::sakoon::सकूं
::sakta::सकता
::sakte::सकते
::sakti::सकती
::sakun::सकूं
::sala::साला
::saleh::साले
::sali::साली
::samajh::समझ
::samajhne::समझने
::samandar::समंदर
::sambhal::संभल
::sambhala::संभाला
::sambhalke::संभलके
::sambhalna::संभालना
::sambhalne::संभालने
::sambhalo::संभालो
::samjha::समझा
::samjhao::समझाओ
::samjhaya::समझाया
::samjhe::समझे
::samjhi::समझी
::samjhkar::समझकर
::samne::सामने
::sanam::सनम
::sapna::सप्ना
::sapne::सप्ने
::sapno::सपनों
::sapnon::सपनों
::sar::सर
::sara::सारा
::sardi::सर्दी
::sare::सारे
::sari::साड़ी
::sarkar::सरकार
::satate::सताते
::satati::सताती
::sath::साथ
::savera::सवेरा
::se::से
::seedha::सीधा
::seedhe::सीधे
::seedhi::सीधी
::shaadi::शादी
::shaam::शाम
::shakal::शकल
::sharam::शरम
::shayad::शायद
::shayiri::शायिरी
::sher::शेर
::shero::शेरो
::shona::शोणा
::shoni::शोणी
::shri::श्री
::shriman::श्रीमान
::shrimati::श्रीमती
::shubh::शुभ
::shudh::शुद्ध
::shuru::शुरू
::si::सी
::sirf::सिर्फ़
::soch::सोच
::socha::सोचा
::socho::सोचो
::sochta::सोचता
::sochte::सोचते
::sochti::सोचती
::soh::सो
::soi::सोई
::sona::सोना
::sone::सोने
::sota::सोता
::sote::सोते
::soti::सोती
::soya::सोया
::soyi::सोयी
::subah::सुबह
::subhan::सुभान
::subhanallah::सुभान अल्लाह
::subzi::सब्ज़ी
::sula::सुला
::sulake::सुलाके
::sulana::सुलाना
::sulane::सुलाने
::sulao::सुलाओ
::sulaun::सुलाऊँ
::sulaya::सुलाया
::sulayenge::सुलायेंगे
::suna::सुना
::sunai::सुनाई
::sunao::सुनाओ
::sunaya::सुनाया
::sunaye::सुनाये
::sunayi::सुनायी
::sune::सुने
::sunega::सुनेगा
::sunenge::सुनेंगे
::sunke::सुनके
::sunna::सुनना
::sunne::सुनने
::suno::सुनो
::sunoge::सुनोगे
::sunogi::सुनोगी
::sunta::सुनता
::sunte::सुनते
::sunti::सुनती
::sununga::सुनूंगा
::sunungi::सुनूंगी
::sussu::सुस्सू
::swaad::स्वाद
::swad::स्वाद
::thab::तब
::tabhi::तभी
::tak::तक
::takdir::तक़दीर
::tam::तम
::tamanna::तमन्ना
::tammana::तमन्ना
::tand::ठंड
::tanda::ठंडा
::tande::ठंडे
::tandi::ठंडी
::tandrusti::तंदरुस्ती
::tandu::ठंडू
::tang::तंग
::taraf::तरफ़
::tarah::तरह
::tat::तत्
::teek::ठीक
::teeka::ठीका
::teekha::तीखा
::teen::तीन
::teesra::तीसरा
::teesri::तीसरी
::tehra::ठहरा
::tehri::ठहरी
::tera::तेरा
::tere::तेरे
::teri::तेरी
::tha::था
::thak::थक
::thand::ठंड
::thanda::ठंडा
::thande::ठंडे
::thandi::ठंडी
::thandu::ठंडू
::thee::थी
::theek::ठीक
::thhe::थे
::thi::थी
::tho::तो
::thoda::थोड़ा
::thode::थोड़े
::thodi::थोड़ी
::thondu::थोंदु
::thu::तू
::thune::तुने
::tika::टिका
::tike::टिके
::tiki::टिकी
::tikki::टिक्की
::toh::तो
::tohfa::तोहफ़ा
::tond::थोंद
::tondu::थोंदु
::toot::टूट
::tthe::थे
::tu::तू
::tujhe::तुझे
::tujhko::तुझको
::tum::तुम
::tumhara::तुमहारा
::tumhare::तुमहारे
::tumhari::तुमहारी
::tumhe::तुमहें
::tumko::तुमको
::tumne::तुमने
::tumse::तुमसे
::tunda::ठंडा
::tung::तंग
::tunna::टुन्ना
::tunni::टुन्नी
::tuut::टूट
::uchal::उछल
::uchalke::उछलके
::uchalna::उछलना
::uchalne::उछलने
::ud::उड़
::udane::उडाने
::udhar::उधर
::udke::उड़के
::udna::उड़ना
::udne::उड़ने
::udta::उड़ता
::udte::उड़ते
::udti::उड़ती
::uff::उफ़
::ullu::उल्लू
::ulta::उल्टा
::un::उन
::unda::अंडा
::unhone::उनहोंने
::unka::उनका
::unke::उनके
::unki::उनकी
::unko::उनको
::unse::उनसे
::upar::ऊपर
::usee::उसी
::usi::उसी
::uska::उसका
::uske::उसके
::uski::उसकी
::usko::उसको
::usme::उसमे
::usne::उसने
::uspar::उस पर
::uspe::उसपे
::uss::उस
::usse::उससे
::utaarke::उतारके
::utaarne::उतारने
::utaaro::उतारो
::utarke::उतारके
::utarne::उतरने
::utaro::उतारो
::uth::उठ
::utha::उठ्ठा
::uthake::उठाके
::uthana::उठाना
::uthane::उठाने
::uthao::उठाओ
::utharke::उतारके
::utharo::उतारो
::uthata::उठाता
::uthati::उठाती
::uthega::उठेगा
::uthegi::उठेगी
::uthenge::उठेंगे
::uthke::उठके
::uthti::उठती
::uthunga::उठूँगा
::uthungi::उठूंगी
::utna::उतना
::utt::उठ
::utta::उठ्ठा
::uttake::उठाके
::uttana::उठाना
::uttane::उठाने
::uttao::उठ्ठाओ
::uttatha::उठाता
::uttathe::उठाते
::uttathi::उठाति
::utte::उठ्ठे
::uttha::उठता
::utthe::उठते
::utti::उठ्ठी
::uttke::उठके
::utto::उठ्ठो
::utttha::उठता
::uttthi::उठती
::vaala::वाला
::vahin::वहीँ
::vaise::वैसे
::vajah::वजह
::vakt::वक़्त
::vala::वाला
::vapas::वापस
::vishwas::विश्वास
::vo::वह
::voh::वह
::waala::वाला
::waale::वाले
::wah::वाह
::wahan::वहाँ
::wahin::वहीँ
::wakt::वक़्त
::wala::वाला
::wale::वाले
::wali::वाली
::wo::वह
::woh::वह
::wohi::वही
::ya::या
::yaad::याद
::yaar::यार
::yahan::यहाँ
::yahi::यही
::yahin::यहीं
::yeh::यह
::yehi::यही
::zabardast::ज़बरदस्त
::zabardasti::ज़बरदस्ती
::zamana::ज़माना
::zamane::ज़माने
::zarurat::ज़रूरत
::zeher::ज़हर
::zid::ज़िद
::ziddi::ज़िद्दी
::zindagi::ज़िंदगी
::zor::ज़ोर
::zulfe::ज़ुल्फ़ें
::zulfein::ज़ुल्फ़ें
::zulm::ज़ुल्म
::zyaada::ज्यादा
::dikhi::दिखी
::re::रे
::shair::शायर
::shayar::शायर
::shairi::शयिरी
::shayari::शयिरी
::sawaal::सवाल
::savaal::सवाल
::sunn::सुन
::dene::देने
::naha::नहा
::nahane::नहाने
::nahaya::नहाया
::nahana::नहाना
::rs.::₹
::tharki::ठरकी
::parivar::परिवार
::sahit::सहित
::saikdon::सैकड़ों
::hasi::हँसी
::hass::हँस
::rakhe::रखे
  