
::amma::அம்மா
::enge::எங்கே
::enna::என்ன
::eppidi::எப்பிடி
::eppo::எப்போ
::iniki::இநீகீ
::ippo::இப்போ
::irruken::இர்ருகென்
::irrukingala::இர்ருகிங்கிளா
::irrukinge::இரருகிங்கே
::irrukingila::இர்ருகிங்கிளா
::irrukire::இர்ருகிரெ
::irruku::இர்ருகு
::iruken::இர்ருகென்
::irukken::இருக்கேன்
::iruku::இர்ருகு
::naan::நான்
::naanga::நாங்க
::naliki::நாழிக்கி
::nee::நீ
::neenga::நீங்க
::neenge::நீன்கே
::nethiki::நேதிகி
::panindu::பண்ணிண்டு
::pannindu::பண்ணிண்டு
::panriya::பண்ணரியா
::poringe::போரிங்கே
::varinge::வறிங்கே
::varuvange::வருவங்கே
::veetile::வீட்டிலே
::veetle::வீட்டிலே
  